name: "Item-Chest-Sorter"
version: "1.1"
load: POSTWORLD

author: "Flo Dörr"
website: "www.flodörr.com"
main: "com.flodoerr.item_chest_sorter.ItemChestSorter"

commands:
  sorter:
    description: main command
    usage: "Usage: /ics [add|select|remove] [sender|receiver]"
    aliases:
      - item-chest-sorter
      - ics
      - itemchestsorter

api-version: "1.15"